config/urls.py
from django.contrib import admin
from django.urls import path, include
from gw.views import base_views

#from gw import views

urlpatterns = [
    # path() 는 url과 뷰를 매핑하는 장고의 함수
    # path(url 경로, 호출할 뷰 함수)
    path("admin/", admin.site.urls),
    
    # gw/ url이 요청되면 views.index를 호출하라는 매핑을 추가
    # viwes.index는 views.py 파일의 index함수를 의미
    #path("gw/", views.index), # 경로를 설정하면 해당 views.py 파일에 index 함수를 추가해야함.
    
    path('gw/', include('gw.urls')),
    
    # [url 분리]
    # from gw import views
    # path("gw/", views.index)
    # 위의 방법은 url 매핑을 추가할 때마다 config/urls.py 파일을 수정해야 한다.
    # 해당 파일은 프로젝트 전반적은 url을 관리하는 파일로, 앱별 url은 url 분리하여 별도로 관리한다.
    # => include 사용
    
    # path('gw/', include('gw.urls'))
    # gw/로 시작하는 페이지를 요청하면 gw/urls.py 파일의 매핑 정보를 읽어서 처리하게 함.
    # gw내에 urls.py 파일을 생성한다.
    
    path('common/', include('common.urls')),
    
    path('', base_views.index, name='index') # '/'에 해당하는 path 설정
]

gw/urls.py
from django.urls import path

from .views import base_views, question_views, answer_views

app_name = 'gw'

urlpatterns = [
    # base_views.py
    path('', base_views.index, name='index'),
    # 기본적으로 매핑할 때, gw/ url을 매핑하므로 ''를 사용한다.
    path('<int:question_id>/', base_views.detail, name='detail'),
    
    # question_views.py
    path('question/create/', question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),
    path('question/vote/<int:question_id>', question_views.question_vote, name='question_vote'),
    
    # answer_views.py
    path('answer/create/<question_id>', answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),
    path('answer/vote/<int:answer_id>', answer_views.answer_vote, name='answer_vote')
]

gw/models.py
from django.db import models
from django.utils.timezone import now
from django.contrib.auth.models import User


# Create your models here.

class Question(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField(default=now)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_question')
    modify_date = models.DateTimeField(null=True, blank=True) # 수정 일시 추가, null 허용, 값 없어도 허용
    voter = models.ManyToManyField(User, related_name='voter_question')
    
    def __str__(self):
        return self.subject
    
class Answer(models.Model):
    # Question모델의 속성에 연결하기 위해 Foreignkey 사용 및
    # 연결된 question이 삭제되면 answer도 삭제되게 설정
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField(default=now)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_answer')
    modify_date = models.DateTimeField(null=True, blank=True) # 수정 일시 추가, null 허용, 값 없어도 허용
    voter = models.ManyToManyField(User, related_name='voter_answer')
    
    # author와 voter가 User 모델과 연결되어 있어, User.question_set으로 Question 데이터에 접근하려고 할 때, 구분이 필요
    # related_name 인수를 추가하여 해결
    # 특정 사용자가 작성한 질문 : some_user.author_question.all(), 특정 사용자가 추천한 질문 : some_user.voter_question.all()

gw/views/answer_views.py
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from ..models import Question, Answer
from ..form import QuestionForm, AnswerForm



@login_required(login_url='common:login') # 로그아웃 상태에서 함수가 호출되면 자동으로 로그인 화면으로 이동시킴
def answer_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user # author 속성에 로그인 계정
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            # return redirect('gw:detail', question_id=question.id)
            # HTML을 호출하는 URL 뒤에 #page를 붙여주면 해당 페이지가 호출되면서 해당 앵커로 스크롤이 이동
            # resolve_url은 실제 호출되는 url 문자열을 리턴하는 장고의 함수
            return redirect('{}#answer_{}'.format(
                resolve_url('gw:detail', question_id=question.id), answer.id
            ))
    else:
        form = QuestionForm()
    context = {'question':question, 'form':form}
    return render(request, 'gw/question_detail.html', context)
    
    
@login_required(login_url='common:login')
def answer_modify(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '수정 권한 없음!')
        return redirect('gw:detail', question_id=answer.question.id)
    if request.method == 'POST':
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.modify_date = timezone.now()
            answer.save()
            # return redirect('gw:detail', question_id=answer.question.id)
            return redirect('{}#answer_{}'.format(
                resolve_url('gw:detail', question_id=answer.question.id), answer.id
            ))
    else:
        form = AnswerForm(instance=answer)
    context = {'form' : form}
    return render(request, 'gw/answer_form.html', context)

@login_required(login_url='common:login')
def answer_delete(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '삭제 권한 없음!')
    else:
        answer.delete()
    return redirect('gw:detail', question_id=answer.question.id)

@login_required(login_url='common:login')
def answer_vote(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user == answer.author:
        messages.error(request, '본인이 작성한 글은 추천할 수 없음')
    else:
        answer.voter.add(request.user)
    # return redirect('gw:detail', question_id=answer.question.id)
    return redirect('{}#answer_{}'.format(
            resolve_url('gw:detail', question_id=answer.question.id), answer.id
    ))

gw/views/base_views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator
from django.db.models import Q  # OR조건으로 데이터를 조회하기위해 Q함수를 사용
from ..models import Question


def index(request):
    # GET 방식으로 호출된 url에서 page 값을 가져오고 디폴트 1로 설정
    page = request.GET.get('page', '1')
    kw = request.GET.get('kw', '') # 검색어
    question_list = Question.objects.order_by('-create_date')
    
    # subject__icontains=kw는 제목에 kw 문자열이 포함되는지를 의미, contains 대신 icontains를 사용하면 대소문자를 가리지 않고 찾음
    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |  # 제목 검색
            Q(content__icontains=kw) |  # 내용 검색
            Q(answer__content__icontains=kw) |  # 답변 내용 검색
            Q(author__username__icontains=kw) |  # 질문 글쓴이 검색
            Q(answer__author__username__icontains=kw)  # 답변 글쓴이 검색
        ).distinct() # distinct() : 중복 질문 제거
    
    paginator = Paginator(question_list, 10) # 페이지당 10개씩 보여준다.
    page_obj = paginator.get_page(page)
        
    context = {'question_list' : page_obj, 'page':page, 'kw': kw} # 템플릿에 전달하기 위해 page, kw 추가
    # render는 파이썬 데이터를 HTML로 반환
    # question_list.html과 같은 파일을 템플릿이라 부름. 별도의 템플릿 디렉터리에 생성한다.
    # 템플릿을 저장할 기본 디렉터리는 settings.py에 TEMPLATES 항목에 설정한다.
    return render(request, 'gw/question_list.html', context)

def detail(request, question_id):
    # question = Question.objects.get(id=question_id)
    question = get_object_or_404(Question, pk=question_id)
    context = {'question' : question}
    return render(request, 'gw/question_detail.html', context)

gw/views/question_views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from ..models import Question
from ..form import QuestionForm



@login_required(login_url='common:login') # 로그아웃 상태에서 함수가 호출되면 자동으로 로그인 화면으로 이동시킴
def question_create(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False) # 임시 저장(데이터베이스 업로드x)
            question.author = request.user # author 속성에 로그인 계정 저장
            question.create_date = timezone.now() # 작성일시 저장
            question.save() # 데이터 실제로 저장
            return redirect('gw:index')
    else:
        form = QuestionForm()
    context = {'form' : form}
    return render(request, 'gw/question_form.html', context) 

              
@login_required(login_url='common:login')
def question_modify(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author: # 글쓴이와 수정자 확인
        messages.error(request, '수정 권한 없음!') # message 로 넌필드 오류 발생시킴
        return redirect('gw:detail', question_id=question.id)
    if request.method == 'POST':
        form = QuestionForm(request.POST, instance=question) # intance를 기준으로 QuestionForm을 생성하지만 request.POST 값으로 덮어씀
        if form.is_valid():
            question = form.save(commit=False)
            question.modify_date = timezone.now() # 수정일시 저장
            question.save()
            return redirect('gw:detail', question_id=question.id)
    else:
        form = QuestionForm(instance=question) # 수정 시, 기존 값을 항목에 채워넣기 위해 instance 사용
    context = {'form' : form}
    return render(request, 'gw/question_form.html', context)
            
@login_required(login_url='common:login')
def question_delete(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '삭제 권한 없음!')
        return redirect('gw:detail', question_id=question.id)
    question.delete()
    return redirect('gw:index')

@login_required(login_url='common:login')
def question_vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user == question.author:
        messages.error(request, '본인이 작성한 글은 추천할수 없습니다')
    else:
        question.voter.add(request.user)
    return redirect('gw:detail', question_id=question.id)

templates/gw/answer_form.html
{% extends 'base.html' %}
{% block content %}
<!-- 답변 수정 -->
<div class="container">
    <form method="post">
        {% csrf_token %}
        {% if form.errors %}
        {% endif %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="content" class="form-label">답변내용</label>
            <textarea class="form-control" rows="10" name="content" id="content">
                {{ form.content.value|default_if_none:'' }}
            </textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock content %}

templates/gw/question_detail.html
{% extends 'base.html' %}
{% block content %}

<!-- {% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}"> -->


<div class="container my-3">
    <!-- message 표시(비정상적으로 질문을 수정할 경우, 오류 표시) -->
     {% if messages %}
     <div class="alert alert-danger my-3" role="alert">
        {% for message in messages %}
        <strong> {{ message.tags }}</strong>
        <ul><li> {{ message.message }} </li></ul>
        {% endfor %}
     </div>
     {% endif %}

    <!-- 질문 -->
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ question.content }}</div>
            <div class="d-flex justify-content-end">
                {% if question.modify_date %}
                <div class="badge bg-light text-dark p-2 text-start mx-3">
                    <div class="mb-2">modified at</div> <!-- 수정 일시 추가 -->
                    <div>{{ question.modify_date }}</div>
                </div>
                {% endif %}
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2">{{ question.author.username }}</div> <!--질문부분 글쓴이 추가-->
                    <div>{{ question.create_date }}</div>
                </div>
            </div>
            <!-- 수정, 삭제 버튼 -->
            <div class="my-3">
                <!-- 추천 버튼 -->
                <a href="javascript:void(0)" data-uri="{% url 'gw:question_vote' question.id  %}"
                    class="recommend btn btn-sm btn-outline-secondary"> 추천
                    <span class="badge rounded-pill bg-success">{{ question.voter.count }}</span>
                </a>

                <!-- 수정, 삭제 버튼 -->
                {% if request.user == question.author %}
                <a href="{% url 'gw:question_modify' question.id %}" 
                    class="btn btn-sm btn-outline-secondary">수정</a>
                <a href="javascript:void(0)" class="delete btn btn-sm btn-outline-secondary"
                    data-uri="{% url 'gw:question_delete' question.id  %}">삭제</a>
                    <!-- javascript:void(0) : 해당 링크를 클릭해도 동작하지 않음 -->
                    <!-- data-uri : 삭제를 실행할 url을 얻기 위해 사용-->
                    <!-- href에 삭제 url을 넣지 않는 이유는 삭제 버튼을 클릭했을 때, 확인창을 띄우기 위해 -->
                {% endif %}
            </div>
        </div>
    </div>

    <!-- 답변 -->
    <h5 class="border-bottom my-3 py-2">{{question.answer_set.count}}개의 답변이 있습니다.</h5>
    {% for answer in question.answer_set.all %}
    <!-- 답변 작성, 수정시에 이동해야할 앵커 태그 추가 -->
    <a id="answer_{{ answer.id }}"></a> 
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
            <div class="d-flex justify-content-end">
                {% if answer.modify_date %}
                <div class="badge bg-light text-dark p-2 text-start mx-3">
                    <div class="mb-2">modified at</div> <!-- 수정 일시 추가 -->
                    <div>{{ answer.modify_date }}</div>
                </div>
                {% endif %}
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2">{{ question.author.username }}</div> <!-- 답변부분 글쓴이 추가-->
                    <div>{{ answer.create_date }}</div>
                </div>
            </div>
            <div class="my-3">
                <!-- 추천 버튼 -->
                <a href="javascript:void(0)" data-uri="{% url 'gw:answer_vote' answer.id  %}"
                    class="recommend btn btn-sm btn-outline-secondary"> 추천
                    <span class="badge rounded-pill bg-success">{{ answer.voter.count }}</span>
                </a>

                {% if request.user == answer.author %}
                <a href="{% url 'gw:answer_modify' answer.id %}"
                    class="btn btn-sm btn-outline-secondary">수정</a>
                <a href="#" class="delete btn btn-sm btn-outline-secondary"
                    data-uri="{% url 'gw:answer_delete' answer.id  %}">삭제</a>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}

    <!-- 답변 등록 -->
    <form action="{% url 'gw:answer_create' question.id %}" method="post" class="my-3">
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->

        <div class="mb-3">
            <label for="content" class="form-label">답변내용</label>
            <!-- 로그인 안되어 있을 때, 답변 내용 입력창 disabled 설정 -->
            <textarea {% if not user.is_authenticated %} disabled {% endif %}
            name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>
{% endblock content %}
{% block script %}
<!-- delete라는 클래스를 포함하는 컴포넌트를 클릭하면 한번더 질문을 하고, 확인을 했을 때, 해당 컨포넌트의 data-uri 값으로 uri를 호출 -->
<script type='text/javascript'>
    const delete_elements = document.getElementsByClassName("delete");
    Array.from(delete_elements).forEach(function(element) {
        element.addEventListener('click', function() {
            if(confirm("정말로 삭제하시겠습니까?")) {
                location.href = this.dataset.uri;
            };
        });
    });

    const recommend_elements = document.getElementsByClassName("recommend");
        Array.from(recommend_elements).forEach(function(element) {
        element.addEventListener('click', function() {
             if(confirm("정말로 추천하시겠습니까?")) {
                location.href = this.dataset.uri;
            };
        });
    });

</script>
{% endblock script %}

templates/gw/question_form.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문 등록</h5>
    <!-- form에 action 태그를 지정하지 않으면 현재 페이지의 URL이 기본 action으로 지정됨 -->
    <!-- 동일한 템플릿을 여러 기능에서 함께 사용할 때 action을 지정하지 않으면 재사용 가능 -->
    <form method="post">
        {% csrf_token %}
        <!-- form.as_p는 폼에 정의된 subject와 content에 해당하는 html코드를 자동으로 생성 -->
        <!-- {{ form.as_p }} -->
        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
        <!-- {{ form.subject.value|default_if_none:'' }} 는 오류가 발생했을 경우 기존 입력값을 유지 -->
        <div class="mb-3">
            <label for="subject" class="form-label">제목</label>
            <input type="text" class="form-control" name="subject" id="subject"
                   value="{{ form.subject.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="content" class="form-label">내용</label>
            <textarea class="form-control" name="content"
                      id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>

{% endblock content%}

templates/gw/question_list.html
{% extends 'base.html' %}
{% load gw_filter %} 
{% block content %}
<!-- {% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}"> -->


<div class="container my-3">
    <!-- 질문 등록하기 창 이동, 찾기 버튼 생성 -->
    <div class="row my-3">
        <div class="col-6">
            <a href="{% url 'gw:question_create' %}" class="btn btn-primary">질문 등록하기</a>
        </div>
        <div class="col-6">
            <div class="input-group">
                <!-- 텍스트창에 입력된 값을 읽기 위해 search_kw를 id로 사용 -->
                <input type="text" id="search_kw" class="form-control" value="{{ kw|default_if_none:'' }}">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
                </div>
            </div>
        </div>
    </div>
    <table class="table">
        <thead>
        <tr class="text-center table-dark">
            <th>번호</th>
            <th style="width:50%">제목</th>
            <th>글쓴이</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if question_list %}
        {% for question in question_list %}
        <tr class="text-center">
            <td>
                <!-- 번호 = 전체건수 - 시작인덱스 - 현재인덱스 + 1 -->
                {{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1 }}
            </td>
            <td class="text-start">
                <!-- <li><a href="/gw/{{ question.id }}">{{ question.subject }}</a></li> -->
                <li>
                    <a href="{% url 'gw:detail' question.id %}">{{ question.subject }}</a>
                    {% if question.answer_set.count > 0 %}
                    <span class="text-danger small mx-2"> {{ question.answer_set.count }}</span>
                    {% endif %}
                </li>
                <!-- 파라미터를 두 개 이상 사용할 경우, 공백 문자 뒤에 추가로 붙여줄 수 있다. -->
            </td>
            <td>{{ question.author.username }}</td> <!-- 글쓴이 추가-->
            <td>{{ question.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="4">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>

    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전 페이지 -->
        {% if question_list.has_previous %}
        <li class="page-item">
            <!-- 파라미터를 직접 코딩하는 방식에서, 값을 읽어 폼에 설정할 수 있도록 변경 -->
            <a class="page-link" data-page="{{ question_list.previous_page_number }}"
            href="javascript:void(0)">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true"
            href="javascript:void(0)">이전</a>
        </li>
        {% endif %}

        <!-- 페이지리스트 -->
        {% for page_number in question_list.paginator.page_range %}
        {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %}
        {% if page_number == question_list.number %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" data-page="{{ page_number }}"
           href="javascript:void(0)">{{ page_number }}</a>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" data-page="{{ page_number }}"
           href="javascript:void(0)">{{ page_number }}</a>
        </li>
        {% endif %}
        {% endif %}
        {% endfor %}

        <!-- 다음 페이지 -->
        {% if question_list.has_next %}
        <li class="page-item">
            <a class="page-link" data-page="{{ question_list.next_page_number }}"
           href="javascript:void(0)">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true"
            href="javascript:void(0)">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- <a href="{% url 'gw:question_create' %}" class="btn btn-primary">질문 등록하기</a> -->
</div>

<!-- page와 kw를 동시에 get 요청할 수 있는 searchForm 추가 -->
<form id="searchForm" method="get" action="{% url 'index' %}">
    <input type="hidden" name="kw" id="kw" value="{{ kw|default_if_none:'' }}">
    <input type="hidden" name="page" id="page" value="{{ page }}"> 
</form>


{% endblock content %}

<!-- page, kw 파라미터 동시에 요청하는 자바스크립트 -->
{% block script %}

<!-- class 속성 값으로 page-link 값을 가지고 있는 링크를 클릭하면 -->
<script type='text/javascript'>
    // 해당 링크의 data-page 속성값을 ㅇ릭어 searchForm의 page 필드에 설정하여 searchForm을 요청함
    const page_elements = document.getElementsByClassName("page-link");
    Array.from(page_elements).forEach(function(element) {
        element.addEventListener('click', function() {
            document.getElementById('page').value = this.dataset.page;
            document.getElementById('searchForm').submit();
        });
    });

    // 검색 버튼을 클릭하면 텍스트장에 입력된 값을 searchForm의 kw 필드에 설정하여 searchForm을 요청함
    const btn_search = document.getElementById("btn_search");
    btn_search.addEventListener('click', function() {
        document.getElementById('kw').value = document.getElementById('search_kw').value;
        document.getElementById('page').value = 1;  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
        document.getElementById('searchForm').submit();
    });
    </script>
{% endblock script %}