common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


app_name = 'common'

urlpatterns = [
    # 로그인 뷰는 django.contrib.auth 앱의 LoginView를 사용하도록 설정
    # LoginView는 registration 템플릿 디렉터리에서 login.html 파일을 찾는데,
    # common 디렉터리의 login.html 파일을 참조할 수 있도록 설정 -> as_view(template_name='common/login.html')
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup, name='signup')
] 

config/urls.py
from django.contrib import admin
from django.urls import path, include
from gw.views import base_views

#from gw import views

urlpatterns = [
    # path() 는 url과 뷰를 매핑하는 장고의 함수
    # path(url 경로, 호출할 뷰 함수)
    path("admin/", admin.site.urls),
    
    # gw/ url이 요청되면 views.index를 호출하라는 매핑을 추가
    # viwes.index는 views.py 파일의 index함수를 의미
    #path("gw/", views.index), # 경로를 설정하면 해당 views.py 파일에 index 함수를 추가해야함.
    
    path('gw/', include('gw.urls')),
    
    # [url 분리]
    # from gw import views
    # path("gw/", views.index)
    # 위의 방법은 url 매핑을 추가할 때마다 config/urls.py 파일을 수정해야 한다.
    # 해당 파일은 프로젝트 전반적은 url을 관리하는 파일로, 앱별 url은 url 분리하여 별도로 관리한다.
    # => include 사용
    
    # path('gw/', include('gw.urls'))
    # gw/로 시작하는 페이지를 요청하면 gw/urls.py 파일의 매핑 정보를 읽어서 처리하게 함.
    # gw내에 urls.py 파일을 생성한다.
    
    path('common/', include('common.urls')),
    
    path('', base_views.index, name='index') # '/'에 해당하는 path 설정
]

gw/urls.py
from django.urls import path

from .views import base_views, question_views, answer_views

app_name = 'gw'

urlpatterns = [
    # base_views.py
    path('', base_views.index, name='index'),
    # 기본적으로 매핑할 때, gw/ url을 매핑하므로 ''를 사용한다.
    path('<int:question_id>/', base_views.detail, name='detail'),
    
    # question_views.py
    path('question/create/', question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),
    path('question/vote/<int:question_id>', question_views.question_vote, name='question_vote'),
    
    # answer_views.py
    path('answer/create/<question_id>', answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),
    path('answer/vote/<int:answer_id>', answer_views.answer_vote, name='answer_vote')
]

gw/views/base_views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator
from django.db.models import Q  # OR조건으로 데이터를 조회하기위해 Q함수를 사용
from ..models import Question


def index(request):
    # GET 방식으로 호출된 url에서 page 값을 가져오고 디폴트 1로 설정
    page = request.GET.get('page', '1')
    kw = request.GET.get('kw', '') # 검색어
    question_list = Question.objects.order_by('-create_date')
    
    # subject__icontains=kw는 제목에 kw 문자열이 포함되는지를 의미, contains 대신 icontains를 사용하면 대소문자를 가리지 않고 찾음
    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |  # 제목 검색
            Q(content__icontains=kw) |  # 내용 검색
            Q(answer__content__icontains=kw) |  # 답변 내용 검색
            Q(author__username__icontains=kw) |  # 질문 글쓴이 검색
            Q(answer__author__username__icontains=kw)  # 답변 글쓴이 검색
        ).distinct() # distinct() : 중복 질문 제거
    
    paginator = Paginator(question_list, 10) # 페이지당 10개씩 보여준다.
    page_obj = paginator.get_page(page)
        
    context = {'question_list' : page_obj, 'page':page, 'kw': kw} # 템플릿에 전달하기 위해 page, kw 추가
    # render는 파이썬 데이터를 HTML로 반환
    # question_list.html과 같은 파일을 템플릿이라 부름. 별도의 템플릿 디렉터리에 생성한다.
    # 템플릿을 저장할 기본 디렉터리는 settings.py에 TEMPLATES 항목에 설정한다.
    return render(request, 'gw/question_list.html', context)

def detail(request, question_id):
    # question = Question.objects.get(id=question_id)
    question = get_object_or_404(Question, pk=question_id)
    context = {'question' : question}
    return render(request, 'gw/question_detail.html', context)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- gw CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Hello, gw!</title>
</head>
<body>
    <!-- 네비게이션바 -->
    {% include "navbar.html" %}
    <!-- 기본 템플릿 안에 삽입될 내용 Start -->
    {% block content %}
    {% endblock content %}
    <!-- 기본 템플릿 안에 삽입될 내용 End -->
     <script src="{% static 'bootstrap.min.js' %}"></script>
     <!-- 자바스크립트 Start -->
    {% block script %}
    {% endblock script %}
     <!-- 자바스크립트 End -->
</body>
</html>

templates/form_errors.html
<!-- 필드 오류와 넌필드 오류를 둘다 구현 -->

{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}

    <!-- 넌필드 오류 -->
    {% for error in form.non_filed_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

templates/navbar.html
<!-- 네비게이션 바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'gw:index' %}">GW</a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:logout' %}"> {{ user.username }} (로그아웃) </a>
                    {% else %}
                    <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                    {% endif %}
                </li>
                <li>
                    {% if not user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:signup' %}">회원가입</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </div>
</nav>